[{"exceptionClass":"java.lang.ArithmeticException","functionName":"int org.example.Main.testThrow(int, int)","timestamps":["2023-04-25T22:29:01.850753"]},{"exceptionClass":"org.example.MyException","functionName":"void org.example.Main.testA()","timestamps":["2023-04-25T22:29:02.139081600","2023-04-25T22:29:02.215735200"]},{"exceptionClass":"org.example.MyException","functionName":"void org.example.Main.test()","timestamps":["2023-04-25T22:29:02.139081600","2023-04-25T22:29:02.215735200"]}]